"""
Condition B: Web-enhanced autoresearch — Batch 6.

Experiments generated by Devstral-Small-2-24B (Q6_K) from fresh paper searches.
Papers referenced:
  [18] AdaGC: "Enhancing LLM Pretraining Stability via Adaptive Gradient Clipping"
       arXiv:2502.11034 — adaptive per-param clipping; here we start with fixed global norm clipping
  [19] ZClip: "Adaptive Spike Mitigation for LLM Pre-Training"
       arXiv:2504.02507 — EMA-based adaptive clipping; try fixed thresholds 1.0 and 0.5
  [20] Moonlight / Muon Scalable (arXiv:2502.16982)
       — muon momentum warmup: currently 0.85→0.95. Try higher targets (0.97, 0.98) and higher start (0.90)
  [21] Power Decay / Optimal LRS (arXiv:2602.06797)
       — architecture search: DEPTH=3 (wider) and DEPTH=5 (deeper) vs current DEPTH=4
  [22] Fantastic Optimizers (arXiv:2509.02046)
       — SCALAR_LR=0.8 and 1.0 not yet tried (0.3-0.7 all explored)
  [23] Batch size scaling — TOTAL_BATCH_SIZE=2**17 (larger batch, fewer steps, each step more stable)

Results appended to results_enhanced.tsv.
Best starting point: 1.118972 (from batch 3).
Script generated with Devstral-Small-2-24B Q6_K via llama-server.
"""
import subprocess
import re
import os
import pathlib

TRAIN_CMD = [os.path.join(os.path.dirname(os.path.abspath(__file__)), ".venv", "Scripts", "python.exe"), "train.py"]
RESULTS_FILE = "results_enhanced.tsv"
BEST_BPB = 1.118972  # best from batch 3


experiments = [
    # [18/19] AdaGC/ZClip: Add global gradient norm clipping at 1.0 (currently NO clipping)
    ("grad_clip=1.0 [AdaGC2025-global-clip]", [
        ("train.py",
         "        loss.backward()\n        x, y, epoch = next(train_loader)",
         "        loss.backward()\n        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)\n        x, y, epoch = next(train_loader)"),
    ]),

    # [19] ZClip: Tighter gradient clipping at 0.5
    ("grad_clip=0.5 [ZClip2025-tighter-clip]", [
        ("train.py",
         "        loss.backward()\n        x, y, epoch = next(train_loader)",
         "        loss.backward()\n        torch.nn.utils.clip_grad_norm_(model.parameters(), 0.5)\n        x, y, epoch = next(train_loader)"),
    ]),

    # [20] Moonlight: Muon momentum warmup target 0.95 → 0.97
    ("muon_warmup_target=0.97 [Moonlight2025-higher-target]", [
        ("train.py",
         "def get_muon_momentum(step):\n    frac = min(step / 300, 1)\n    return (1 - frac) * 0.85 + frac * 0.95",
         "def get_muon_momentum(step):\n    frac = min(step / 300, 1)\n    return (1 - frac) * 0.85 + frac * 0.97"),
    ]),

    # [20] Moonlight: Muon momentum warmup target 0.95 → 0.98
    ("muon_warmup_target=0.98 [Moonlight2025-max-target]", [
        ("train.py",
         "def get_muon_momentum(step):\n    frac = min(step / 300, 1)\n    return (1 - frac) * 0.85 + frac * 0.95",
         "def get_muon_momentum(step):\n    frac = min(step / 300, 1)\n    return (1 - frac) * 0.85 + frac * 0.98"),
    ]),

    # [20] Moonlight: Muon momentum warmup start 0.85 → 0.90 (faster stabilization)
    ("muon_warmup_start=0.90 [Moonlight2025-higher-start]", [
        ("train.py",
         "def get_muon_momentum(step):\n    frac = min(step / 300, 1)\n    return (1 - frac) * 0.85 + frac * 0.95",
         "def get_muon_momentum(step):\n    frac = min(step / 300, 1)\n    return (1 - frac) * 0.90 + frac * 0.95"),
    ]),

    # [21] Architecture: DEPTH=3 (shallower, wider model)
    ("DEPTH=3 [OptimalLRS2026-architecture]", [
        ("train.py",
         "DEPTH = 4               # shallower, more width per layer",
         "DEPTH = 3               # even shallower, more width per layer (architecture search)"),
    ]),

    # [21] Architecture: DEPTH=5 (deeper model)
    ("DEPTH=5 [OptimalLRS2026-deeper]", [
        ("train.py",
         "DEPTH = 4               # shallower, more width per layer",
         "DEPTH = 5               # deeper model (architecture search)"),
    ]),

    # [22] Fantastic Optimizers: SCALAR_LR=0.8 (not yet tried; 0.3-0.7 all explored)
    ("SCALAR_LR=0.8 [Fantasia2025-higher-scalar]", [
        ("train.py",
         "SCALAR_LR = 0.5         # learning rate for per-layer scalars (Adam)",
         "SCALAR_LR = 0.8         # higher scalar LR not yet tried (Fantastic Optimizers 2025)"),
    ]),

    # [22] Fantastic Optimizers: SCALAR_LR=1.0 (match EMBEDDING_LR)
    ("SCALAR_LR=1.0 [Fantasia2025-match-embed]", [
        ("train.py",
         "SCALAR_LR = 0.5         # learning rate for per-layer scalars (Adam)",
         "SCALAR_LR = 1.0         # scalar LR matching embedding LR (Fantastic Optimizers 2025)"),
    ]),

    # [23] Batch size scaling: 2**16 → 2**17 (larger batch = more stable gradients per step)
    ("TOTAL_BATCH_SIZE=2**17 [BatchScaling2025]", [
        ("train.py",
         "TOTAL_BATCH_SIZE = 2**16 # ~65K tokens \u2014 maximize optimizer steps",
         "TOTAL_BATCH_SIZE = 2**17 # ~130K tokens \u2014 larger batch for gradient stability"),
    ]),
]


def read_file(path):
    with open(path, encoding='utf-8') as f:
        return f.read()


def write_file(path, content):
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)


def run_experiment(desc, changes, best_bpb):
    print(f"\n{'='*60}")
    print(f"Experiment: {desc}")
    print(f"{'='*60}")

    originals = {}
    for filepath, old_str, new_str in changes:
        if filepath not in originals:
            originals[filepath] = read_file(filepath)

    for filepath, old_str, new_str in changes:
        content = read_file(filepath)
        if old_str not in content:
            print(f"  SKIP: old_str not found: {old_str[:60]!r}")
            for fp, orig in originals.items():
                write_file(fp, orig)
            return best_bpb, None
        write_file(filepath, content.replace(old_str, new_str, 1))

    for filepath in originals:
        subprocess.run(["git", "add", filepath], capture_output=True)
    subprocess.run(["git", "commit", "-m", f"web-exp6: {desc}"], capture_output=True)
    commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                            capture_output=True, text=True).stdout.strip()

    print(f"  Training... ", end="", flush=True)
    result = subprocess.run(TRAIN_CMD, capture_output=True, text=True, timeout=600,
                            env={**os.environ, "PYTHONIOENCODING": "utf-8"})

    log = result.stdout + result.stderr
    with open("run.log", "w", encoding="utf-8") as f:
        f.write(log)

    val_match = re.search(r"^val_bpb:\s+([\d.]+)", log, re.M)
    vram_match = re.search(r"^peak_vram_mb:\s+([\d.]+)", log, re.M)

    if not val_match:
        print("CRASH")
        for fp, orig in originals.items():
            write_file(fp, orig)
        subprocess.run(["git", "add"] + list(originals.keys()), capture_output=True)
        subprocess.run(["git", "commit", "-m", f"revert: {desc} (crash)"], capture_output=True)
        with open(RESULTS_FILE, "a", encoding="utf-8") as f:
            f.write(f"{commit}\t0.000000\t0.0\tcrash\t{desc}\n")
        return best_bpb, None

    val_bpb = float(val_match.group(1))
    vram = float(vram_match.group(1)) / 1024 if vram_match else 0

    if val_bpb < best_bpb:
        status = "keep"
        print(f"KEEP: {val_bpb:.6f} (was {best_bpb:.6f}, -{best_bpb - val_bpb:.6f})")
        best_bpb = val_bpb
    else:
        status = "discard"
        print(f"DISCARD: {val_bpb:.6f} (best: {best_bpb:.6f})")
        subprocess.run(["git", "reset", "--hard", "HEAD~1"], capture_output=True)

    with open(RESULTS_FILE, "a", encoding="utf-8") as f:
        f.write(f"{commit}\t{val_bpb:.6f}\t{vram:.1f}\t{status}\t{desc}\n")

    return best_bpb, val_bpb


if __name__ == "__main__":
    best = BEST_BPB
    print(f"Starting web-enhanced experiments batch 6 (Condition B).")
    print(f"Starting val_bpb: {best} (best from batch 3)")
    print(f"Running {len(experiments)} web-sourced experiments (Devstral-generated)...")

    for i, (desc, changes) in enumerate(experiments, 1):
        print(f"\n[{i}/{len(experiments)}]")
        best, val = run_experiment(desc, changes, best)

    print(f"\n{'='*60}")
    print(f"DONE. Final best val_bpb: {best:.6f}")
    print(f"Results saved to {RESULTS_FILE}")
    print(f"\nCompare with baseline: python analyze.py")
